version: '3.8'

services:
    postgres:
        image: postgres:16
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=feedback
        volumes:
            - postgres:/var/lib/postgresql/data

    feedback:
        image: feedback
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/feedback
            - SECRET_KEY=SOMEKEY
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=9999
        depends_on:
            - postgres

volumes:
    postgres: {}
