"""feedback resp summary

Revision ID: 12838df22a26
Revises: 3764fe889596
Create Date: 2024-12-16 01:40:18.024303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12838df22a26'
down_revision: Union[str, None] = '3764fe889596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_response', sa.Column('summarized', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_response', 'summarized')
    # ### end Alembic commands ###
