"""feedback title

Revision ID: 3764fe889596
Revises: 48dc691599a4
Create Date: 2024-11-25 00:34:12.016729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3764fe889596"
down_revision: Union[str, None] = "48dc691599a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feedback_session", sa.Column("title", sa.String(), nullable=False))
    op.create_unique_constraint(None, "feedback_session", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feedback_session", type_="unique")
    op.drop_column("feedback_session", "title")
    # ### end Alembic commands ###
