"""feedback session summary

Revision ID: b98f952a3456
Revises: 12838df22a26
Create Date: 2024-12-16 02:02:23.269570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98f952a3456'
down_revision: Union[str, None] = '12838df22a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_session', sa.Column('summarized', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_session', 'summarized')
    # ### end Alembic commands ###
